version: '3.1'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - RAILS_ENV=${RAILS_ENV:-development}
        command: bash #bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        restart: always
        volumes:
            - .:/app
            - bundle_cache:/bundle
        stdin_open: true
        tty: true
        #ports:
        #    - "3000:3000"
        #depends_on:
        #    - db
        environment:
            - RAILS_ENV=${RAILS_ENV:-development}
volumes:
    bundle_cache:
        external: true
